name: e_masjid
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  flutter_staggered_animations: ^1.1.1
  flutter_screenutil: ^5.9.1
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.0

  # Firebase (gunakan versi stabil dan terbaru)
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.1.6

  # State Management
  provider: ^6.1.1
  get_storage: ^2.1.1

  convex_bottom_bar: ^3.0.0
  bubble_bottom_bar: ^2.0.0

  webview_flutter: ^4.2.3
  flutter_widget_from_html: ^0.16.0
  html: ^0.15.4
  http_auth: ^1.0.4
  get: ^4.6.6
  email_validator: ^3.0.0
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  flutter_datetime_picker: ^1.5.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  http: ^1.4.0
  package_info_plus: ^8.3.0

  cloudinary_public: ^0.23.1
  image_picker: ^1.0.7
  dio: ^5.8.0+1

dependency_overrides:
  file: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: fonts/RobotoMono-Italic.ttf
          weight: 400

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
  #     - family: Schyler
  #      fonts:
  #        - asset: fonts/Schyler-Regular.ttf
  #        - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/e_masjid_web.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/e_masjid_web.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/e_masjid_web.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/e_masjid_web.png"
