// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBS2CxCMHxEAciF1RODhAVlntAqk2Lcxw',
    appId: '1:231218713009:web:1f6906cc2977a46cf02d90',
    messagingSenderId: '231218713009',
    projectId: 'e-masjid-61430',
    authDomain: 'e-masjid-61430.firebaseapp.com',
    storageBucket: 'e-masjid-61430.firebasestorage.app',
    measurementId: 'G-FXEDSL4LSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8fxicQTXCZXH2keqzidtqHeQwEJbG0qU',
    appId: '1:231218713009:android:44d9fc642e942979f02d90',
    messagingSenderId: '231218713009',
    projectId: 'e-masjid-61430',
    storageBucket: 'e-masjid-61430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJm1J2-rzXVFTPa0ZeVyn8uNPLrwabKg4',
    appId: '1:231218713009:ios:c66471a1727f5ccaf02d90',
    messagingSenderId: '231218713009',
    projectId: 'e-masjid-61430',
    storageBucket: 'e-masjid-61430.firebasestorage.app',
    iosBundleId: 'com.example.eMasjid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJm1J2-rzXVFTPa0ZeVyn8uNPLrwabKg4',
    appId: '1:231218713009:ios:c66471a1727f5ccaf02d90',
    messagingSenderId: '231218713009',
    projectId: 'e-masjid-61430',
    storageBucket: 'e-masjid-61430.firebasestorage.app',
    iosBundleId: 'com.example.eMasjid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBS2CxCMHxEAciF1RODhAVlntAqk2Lcxw',
    appId: '1:231218713009:web:559b2c3500f7e362f02d90',
    messagingSenderId: '231218713009',
    projectId: 'e-masjid-61430',
    authDomain: 'e-masjid-61430.firebaseapp.com',
    storageBucket: 'e-masjid-61430.firebasestorage.app',
    measurementId: 'G-P5BWKB8WXD',
  );
}
